sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - bash .travis/build_swap.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: kyber-swap
    region: ap-southeast-1
    local_dir: dist
    upload_dir: $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      all_branches: true

  - provider: script
    script: bash .travis/awx_job_launch.sh $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|staging|master$
