sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

script:
  - echo 'skip npm test'

install:
  - echo 'skip install'

jobs:
  include:
    - stage: install
      install: npm ci

    - stage: build
      script: npm run build_auto_production
      if: branch = master
    - stage: build
      script: npm run build_auto_ropsten
      if: branch = develop OR branch = master
    - stage: build
      script: npm run build_auto_staging_limit_order
      if: branch = staging
    - stage: build
      script: npm run build_auto_dev
      if: branch = develop
    - stage: build
      script: npm run build-ropsten
      if: branch = master
    - stage: build
      script: npm run build-staging
      if: branch = master

    - stage: deploy
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: ropsten.kyber.network
          region: ap-southeast-1
          acl: public_read
          local_dir: dist/ropsten
          skip_cleanup: true
          on:
            branch: master
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: ropsten.kyber.network
          region: ap-southeast-1
          acl: public_read
          local_dir: dist/ropsten
          upload-dir: swap
          skip_cleanup: true
          on:
            branch: master
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: ropsten.kyber.network
          region: ap-southeast-1
          acl: public_read
          local_dir: dist/ropsten
          upload-dir: transfer
          skip_cleanup: true
          on:
            branch: master
      if: branch = master
    - stage: deploy
      deploy:
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: staging-swap.knstats.com
        region: ap-southeast-1
        acl: public_read
        local_dir: dist/staging
        skip_cleanup: true
        on:
          branch: master
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: staging-swap.knstats.com
        region: ap-southeast-1
        acl: public_read
        local_dir: dist/staging
        upload-dir: swap
        skip_cleanup: true
        on:
          branch: master
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: staging-swap.knstats.com
        region: ap-southeast-1
        acl: public_read
        local_dir: dist/staging
        upload-dir: transfer
        skip_cleanup: true
        on:
          branch: master
      if: branch = master
    - stage: deploy
      deploy:
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: kyber-swap
        region: ap-southeast-1
        local_dir: public
        upload_dir: $TRAVIS_BRANCH
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^develop|staging|master$
      - provider: script
        script: bash .travis/awx_job_launch.sh $TRAVIS_BRANCH
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^develop|staging|master$
