sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - npm run build-ropsten
  - mkdir upload
  - mv dist/ropsten/*.css upload
  - mv dist/ropsten/*.js upload

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-swap.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: upload
    skip_cleanup: true
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-swap.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: upload
    upload-dir: swap
    skip_cleanup: true
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-swap.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: upload
    upload-dir: transfer
    skip_cleanup: true
    on:
      branch: develop
